# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Low', 'Low'), ('High', 'High')], max_length=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Done', 'Done'), ('To Do', 'To Do'), ('Doing', 'Doing')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='task1_status',
            field=models.CharField(choices=[('Done', 'Done'), ('To Do', 'To Do'), ('Doing', 'Doing')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='task2_status',
            field=models.CharField(choices=[('Done', 'Done'), ('To Do', 'To Do'), ('Doing', 'Doing')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='task3_status',
            field=models.CharField(choices=[('Done', 'Done'), ('To Do', 'To Do'), ('Doing', 'Doing')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='task4_status',
            field=models.CharField(choices=[('Done', 'Done'), ('To Do', 'To Do'), ('Doing', 'Doing')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='task5_status',
            field=models.CharField(choices=[('Done', 'Done'), ('To Do', 'To Do'), ('Doing', 'Doing')], max_length=5),
        ),
    ]
