# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181029_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('1', 'To Do'), ('2', 'Doing'), ('3', 'Done')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='task1_status',
            field=models.CharField(choices=[('1', 'To Do'), ('2', 'Doing'), ('3', 'Done')], default='To Do', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='task2_status',
            field=models.CharField(blank=True, choices=[('1', 'To Do'), ('2', 'Doing'), ('3', 'Done')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='task3_status',
            field=models.CharField(blank=True, choices=[('1', 'To Do'), ('2', 'Doing'), ('3', 'Done')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='task4_status',
            field=models.CharField(blank=True, choices=[('1', 'To Do'), ('2', 'Doing'), ('3', 'Done')], max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='task5_status',
            field=models.CharField(blank=True, choices=[('1', 'To Do'), ('2', 'Doing'), ('3', 'Done')], max_length=5),
        ),
    ]
