# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180917_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='anon.png', upload_to='img'),
        ),
    ]
