# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posttest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTest',
        ),
    ]
